events {}

http {

    upstream front_upstream {
        server front:80;
    }

    upstream bff_upstream {
        server cloud-bff:8080;
    }

    upstream keycloak_upstream {
        server keycloak:8080;
    }


    # =====================================================
    # HTTP -> HTTPS
    # =====================================================

    server {
        listen 80;
        server_name localhost;

        return 308 https://$host$request_uri;
    }


    # =====================================================
    # HTTPS gateway
    # =====================================================

    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate     /etc/nginx/certs/localhost.crt;
        ssl_certificate_key /etc/nginx/certs/localhost.key;

        ssl_protocols TLSv1.2 TLSv1.3;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port 443;


        # Keycloak
        location /keycloak/ {
            proxy_pass http://keycloak_upstream/keycloak/;
        }

        # BFF API
        location /api/ {
            proxy_pass http://bff_upstream;
        }

        # Spring Security OAuth2 authorization endpoint
        location /oauth2/ {
            proxy_pass http://bff_upstream;
        }

        # Spring Security OAuth2 callback
        location /login/ {
            proxy_pass http://bff_upstream;
        }

        # Logout
        location = /logout {
            proxy_pass http://bff_upstream;
        }

        # Angular — MUST remain last/fallback
        location / {
            proxy_pass http://front_upstream;
        }
    }
}
